### PR TITLE
Throw when duplicate selectors are found

### LINKED ISSUE #59: Bug: router not updated after fixing a selector collision
Steps to reproduce:
- have a basic system working
- deploy it: npx hardhat deploy --network local --clear
- create a new module/contract with a function similar to other contract (same name and parameters)
- deploy it: npx hardhat deploy --network local --clear
    - you're going to see an error found by the tooling indicating there's a selector collision
- rename the function on the new contract created
- try to deploy it again: npx hardhat deploy --network local --clear
    - the error is not detected by the tooling (in fact the router is not updated) but by the solidity compiler. In order to continue working the dev should delete manually the router.

### PR DESCRIPTION
**Pull request by ajsantander**
Fix #59

### CODE REVIEW

File: packages/deployer/subtasks/generate-router.js [hunk 1]
```diff
@@ -114,11 +114,31 @@ async function _getAllSelectors(contractsPaths) {
...
+  if (duplicates.length > 0) {
+    const ocurrences = [];
+    duplicates.map((duplicate) => {
+      const cases = selectors.filter((s) => s.selector === duplicate);
+      ocurrences.push(
+        `  > ${cases[0].name} found in modules ${cases.map((c) => c.contractName)} - ${duplicate}\n`
+      );
+    });
+
+    throw new Error(`Duplicate selectors found!\n${ocurrences.join('')}`);
```
Comment (leomassazza) [inline packages/deployer/subtasks/generate-router.js:138]:
```suggestion
      ocurrences.push(
        `  > ${cases[0].name} found in modules ${cases.map((c) => c.contractName)} - ${duplicate}`
      );
    });

    throw new Error(`Duplicate selectors found!\n${ocurrences.join('/n')}`);
```

**Review by leomassazza — APPROVED** [review]
Approved with only one np
