### PR TITLE
Fix modules updates

### LINKED ISSUE #168: Add a black boxed tests for the Generated Router

### LINKED ISSUE #224: When deleting a module after anew deployment, the following one fails
Steps to  repro:
1. Do a `--clean` deployment
2. Delete any Module from `contracts/modules`
3. Try to deploy again, without `--clean`, it will fail.

**Important!**
After fixing, handle TODOs in `deploy.spec.js`
https://github.com/Synthetixio/synthetix-v3/pull/225/files#diff-aac39963cd93065b128b68f10fa781d224942fc7fbf0e1c907d6cd3e06361cc4R71

### PR DESCRIPTION
**Pull request by mjlescano**
Fixes #224
Closes #168

Coverage after being able to enable updates test is on `91%~` 🙌 :
Captura de Pantalla 2021-10-08 a la(s) 11 44 17

### CODE REVIEW

File: packages/deployer/tasks/deploy.js [hunk 1]
```diff
@@ -51,13 +51,13 @@ task(TASK_DEPLOY, 'Deploys all system modules')
 
       await hre.run(SUBTASK_PREPARE_DEPLOYMENT, taskArguments);
       await hre.run(SUBTASK_PRINT_INFO, taskArguments);
-      await hre.run(TASK_COMPILE, { force: false, quiet: true });
+      await hre.run(TASK_COMPILE, { force: true, quiet: true });
```
Comment (mjlescano) [inline packages/deployer/tasks/deploy.js:54]: This is the real fix for the PR. Before hadhat wasn't refreshing build info when deleting a contract. This will cause the  build to take a little longer, but is necessary for our use case.
