### PR TITLE
Fix modules constants names on router

### LINKED ISSUE #94: Consider using camelcase in module constants in the router

### PR DESCRIPTION
**Pull request by mjlescano**
Closes #94

This also fixes the __*very unlikely*__ case were the modules `BearableModule` & `BearAbleModule` would both generate the `_BEARABLEMODULE` constant and collide, instead of `_BEARABLE_MODULE` & `_BEAR_ABLE_MODULE`

### CODE REVIEW

File: packages/deployer/subtasks/generate-router.js [hunk 1]
```diff
@@ -99,22 +99,33 @@ function _renderSelectors({ binaryData }) {
...
 }
 
+/**
+ * Converts the contracts name to private _CONSTANT_CASE format.
+ * E.g.:
+ *   'BearableModule' => '_BEARABLE_MODULE'
+ *   'Proxy' => '_PROXY'
+ *   'ERC20Token' => '_ERC20_TOKEN'
+ */
+function _contractConstantName(name) {
```
Comment (ajsantander) [inline packages/deployer/subtasks/generate-router.js:125]: Maybe a more intuitive name like _toConstantCase(…)?

**Review by ajsantander — APPROVED** [review]
Minor nit
