### PR TITLE
Remove comms type 1

### LINKED ISSUE #111: Fix intermodular comms simple way
Atm tests are failing because msg.sender is lost when using the casting method (comms type 1). This method should be removed for the time being.

### PR DESCRIPTION
**Pull request by ajsantander**
Fix #111

### CODE REVIEW

File: packages/deployer/test/sample-project/test/helpers/initializer.js [hunk 1]
```diff
@@ -22,19 +22,7 @@ function bootstrap() {
 
 async function deploySystemIfNeeded() {
   if (!proxyAddress) {
-    const deployment = getDeployment();
```
Comment (ajsantander) [inline packages/deployer/test/sample-project/test/helpers/initializer.js:25]: Had to remove this:

The idea of this was to avoid local deployments every time tests are ran. Worked nicely when just changing test files, but it doesn't detect when contract changes and re-deploy the system.

Without this, every time tests are run, the system will be re-deployed. It's fast enough for now anyway.

**Review by mjlescano — APPROVED** [review]

**Review by i-stam — APPROVED** [review]
