### PR TITLE
Fix quiet option when compiling contracts

### LINKED ISSUE #311: Update forcing of hardhat output only on required function calls
Right now, if the `quiet` option is enabled, we are completely disabling `console.log` ([here](https://github.com/Synthetixio/synthetix-v3/blob/main/packages/deployer/tasks/deploy.js#L78:L94)) on the entire process and making it unavailable for the entire process.

Instead of doing that, we could just disable it during compilation, e.g.:
```javascript
// DISABLE console.log HERE
await hre.run(TASK_COMPILE, { force: true, quiet: true });
// RE-ENABLE console.log HERE
```
 
 Btw, check if hardhat fixed their quiet parameter

### PR DESCRIPTION
**Pull request by mjlescano**
Closes #311

### CODE REVIEW

File: packages/deployer/tasks/deploy.js [hunk 1]
```diff
@@ -70,25 +66,25 @@ task(TASK_DEPLOY, 'Deploys all system modules')
...
       throw err;
-    } finally {
-      _forceSilenceHardhat(false, quiet);
     }
   });
 
 /*
  * Note: Even though hardhat's compile task has a quiet option,
  * it stil prints some output. This is a hack to completely silence
  * output during deployment.
```
Comment (mjlescano) [inline packages/deployer/tasks/deploy.js:75]:
```suggestion
 * output during compile task run.
```

**Review by leomassazza — APPROVED** [review]

**Review by ajsantander — APPROVED** [review]
